apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dremio-coordinator-data
  namespace: dremio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
