apiVersion: v1
kind: ServiceAccount
metadata:
  name: dremio-elastic
  namespace: dremio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dremio-elastic-role
  namespace: dremio
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dremio-elastic-binding
  namespace: dremio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dremio-elastic-role
subjects:
  - kind: ServiceAccount
    name: dremio-elastic
    namespace: dremio
---
# GHCR secret will be created by deploy.sh
