apiVersion: v1
kind: ServiceAccount
metadata:
  name: dremio-elastic
  namespace: dremio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dremio-elastic-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dremio-elastic
    namespace: dremio
---
# GHCR secret will be created by deploy.sh
