apiVersion: v1
kind: ConfigMap
metadata:
  name: dremio-config
  namespace: dremio
data:
  dremio.conf: |
    paths: {
      local: "/opt/dremio/data"
      dist: "pdfs:///opt/dremio/dist"
    }
    services: {
      coordinator.enabled: true,
      coordinator.master.enabled: true,
      coordinator.master.embedded-zookeeper.enabled: true,
      coordinator.web.port: 9047,
      coordinator.web.auth.type: "internal",
      executor.enabled: false,
      executor.elastic.enabled: true,
      executor.elastic.min_executors: 0,
      executor.elastic.max_executors: 2,
      executor.elastic.max_executors_large: 8,
      executor.elastic.kubernetes.namespace: "dremio",
      executor.elastic.kubernetes.pod_template: "dremio-executor-small",
      executor.elastic.kubernetes.pod_template_large: "dremio-executor-large",
      web-admin.host: "0.0.0.0",
      web-admin.port: 45679
    }
