apiVersion: v1
kind: Service
metadata:
  name: dremio-coordinator-ingress
  namespace: dremio
spec:
  type: ClusterIP
  ports:
    - port: 9047
      targetPort: 9047
      name: web
    - port: 45678
      targetPort: 45678
      name: rpc
    - port: 2181
      targetPort: 2181
      name: zk
    - port: 32010
      targetPort: 32010
      name: flight
  selector:
    app: dremio
    role: coordinator
