apiVersion: v1
kind: Secret
metadata:
  name: minio-dremio-root
  namespace: dremio
type: Opaque
stringData:
  rootUser: "dremio-minio-admin"
  rootPassword: "***********$2026!xR7"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-dremio-credentials
  namespace: dremio
type: Opaque
stringData:
  access_key: "dremio-svc"
  secret_key: "changeme"
