apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-executor-large
  namespace: dremio
  labels:
    app: dremio
    role: executor
    tier: large
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 0
  selector:
    matchLabels:
      app: dremio
      role: executor
      tier: large
  serviceName: dremio-executor
  template:
    metadata:
      labels:
        app: dremio
        role: executor
        tier: large
    spec:
      containers:
        - name: executor
          image: ghcr.io/rusha-corp/dremio-oss:2026.05.7
          imagePullPolicy: Always
          env:
            - name: DREMIO_CONF_DIR
              value: /opt/dremio/conf
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DREMIO_MAX_MEMORY_SIZE_MB
              value: "14336"
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 120
          ports:
            - containerPort: 45678
              name: inter-node
          readinessProbe:
            tcpSocket:
              port: 45678
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            tcpSocket:
              port: 45678
            failureThreshold: 300
            periodSeconds: 2
          resources:
            limits:
              cpu: "4"
              ephemeral-storage: 20Gi
              memory: 16Gi
            requests:
              cpu: "2"
              ephemeral-storage: 10Gi
              memory: 8Gi
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - mountPath: /opt/dremio/conf
              name: dremio-config
            - mountPath: /opt/dremio/dist
              name: dremio-dist
            - mountPath: /opt/dremio/data
              name: dremio-local
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/hostname: vmi1594378.contaboserver.net
      securityContext:
        fsGroup: 0
      serviceAccount: dremio-elastic
      serviceAccountName: dremio-elastic
      subdomain: dremio-executor
      terminationGracePeriodSeconds: 1800
      volumes:
        - configMap:
            name: dremio-executor-config-large
          name: dremio-config
        - name: dremio-dist
          persistentVolumeClaim:
            claimName: dremio-dist
  volumeClaimTemplates:
    - metadata:
        name: dremio-local
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: longhorn
